### PR TITLE
Add Systemd service file

### PR DESCRIPTION
**Pull request by Rjasuja**
Adding service file to support systemd initialization manager

Issue: #35
Test: Verified service on ubuntu setup

Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>

### CODE REVIEW

**Comment by avinash-palleti** [comment]
@lucasdemarchi I verified it on my system. 

"./autogen.sh c " able to find all paths and no configure errors. Not sure why Travis build is failing.

**Comment by lucasdemarchi** [comment]
```
checking systemd system unit dir... configure: error: systemd system unit directory is required
```

From https://travis-ci.org/01org/mavlink-router/builds/230678099?utm_source=github_status&utm_medium=notification

@avinash-palleti it's failing because now systemd is mandatory (unless disabled).  In your system it may succeeded since you have systemd installed, so it's able to retrieve the systemd system unit dir via pkgconfig.

**Comment by lucasdemarchi** [comment]
This is a diff on top of your patch that should make it work:
https://hastebin.com/jozuvarini

I also reworded the readme a little bit, too.

**Comment by lucasdemarchi** [comment]
Oh... and also removed the user unit dir since we aren't using it (nor I think we will ever do).
https://hastebin.com/sediqunoti

**Pull request closed without merging**
