### PR TITLE
build: Add helpers for static analysis

### PR DESCRIPTION
**Pull request by anselmolsm**

### CODE REVIEW

**Comment by dagar** [comment]
Coverity works pretty well on travis-ci.
https://scan.coverity.com/travis_ci

https://travis-ci.org/01org/mavlink-router

**Comment by lucasdemarchi** [comment]
Yep, if we are only uploading to scan.coverity.com, then we could just setup a CI like travis to do that.  I'd rather configure a cron job on it to do once a day or once a week instead of going with the suggested configuration of having a separate branch.

**Comment by anselmolsm** [comment]
No objections. Just need to obtain some rights on the github repo, to enable the sync with travis. I'll verify this.

**Comment by lucasdemarchi** [comment]
Ok. Meanwhile this is applied so we can use it. Thanks.

**Pull request closed without merging**
